from . import lead_scoring_rule
from . import crm_lead
from . import res_partner
from . import sale_order
from . import pipeline_analytics
from . import crm_email_template
from . import sales_forecast
from . import customer_journey
from . import followup_rule
from . import deal_room
